#!/usr/bin/env bash
##############################################################
# Process the config.xml file generated by first startup.
# Make sure to do if/else in the changes since the config file
# will only be created if there is none. I.e., don't mess up
# any changes already made by the user!
##############################################################

# Exit if any of the intermediate steps fail
set -e

# Extract input values
eval "$(jq -r '@sh "CONF=\(.conf) GUI=\(.gui) CONTAINER_ID=\(.container_id)"')"


# Define funtion to extract values
function get_value {
    KEY="${1}"
    echo $(grep "<${KEY}>" "${CONF}" | sed -e 's,.*<'${KEY}'>\([^<]*\)</'${KEY}'>.*,\1,g')
}

# Make sure we got a file name that is config.xml
if ![[ -f "${CONF}" ]];then
  printf "Could not find the config file. Check your paths.\n" >&2
  exit 1
fi

# Check if GUI should be used or not
if [[ "${GUI}" == 1 ]];then
  sed -i -- 's/gui enabled="false"/gui enabled="true"/g' "${CONF}"
else
  sed -i -- 's/gui enabled="true"/gui enabled="false"/g' "${CONF}"
fi

# Get the API key
APIKEY=$(get_value "apikey")

# Save outputs
jq -n --arg apikey "$APIKEY"  --arg what "$CONTAINER_ID" '{"apikey":$apikey, "what":$what}'

# Restart the container
docker restart "${CONTAINER_ID}" >/dev/null 2>&1
